title: "Epidemic modelling &ndash; Some notes, maths, and code"
author: "Simon Dobson"
email: simon.dobson@st-andrews.ac.uk
copyright: "2023"
#logo: logo.png

repository:
  url: https://github.com/simoninireland/introduction-to-epidemics

launch_buttons:
  notebook_interface: "classic"

execute:
  execute_notebooks: "off"

bibtex_bibfiles:
  - bibliography.bib

html:
  use_repository_button: true
